packages:
  - plugins/*
onlyBuiltDependencies:
  - esbuild
  - vue-demi

catalog:
  '@vuepress/bundler-vite': 2.0.0-rc.23
  '@vuepress/bundler-webpack': 2.0.0-rc.23
  '@vueuse/core': ^13.1.0
  sass: ^1.86.3
  sass-embedded: ^1.86.3
  sass-loader: ^16.0.5
  vue: ^3.5.13
  vuepress: 2.0.0-rc.23
