//export * from './assignDefaultLocaleOptions'
export * from './resolveMarkdownHintLocales'
export * from './resolveThemeOptions'
//export * from './assignDefaultOptions'
export * from './assignPlugins'
